### ISSUE TITLE
SCK and MOSI pins swapped

### ISSUE THREAD

**Issue by turtlekiosk** [codingcatgirl/split-flap-fae-pcb#1]
Hi, this is a great design and I got it fabbed at JLC. I was trying to program the atmega using the ISP pins and I noticed the MOSI and SCK pins are swapped on the board!

**Comment by codingcatgirl** [comment]
What do you mean, "swapped"? Are they labeled incorrectly? That's not been the case when i flashed them.

So i assume you just have a programmer that has a 6-pin connector for the ISP headers and those two pins are swapped on it? That's unfortunate then, but would indicate that your programmer probably just uses a non-standard layout?

**Comment by turtlekiosk** [comment]
Ah sorry, you're right, the actual pinout is correct. I didn't notice because I was using an Arduino as ISP to flash the chips so I was manually inserting the leads into each pin, but I do think the labels for SCK and MOSI are labeled incorrectly.

**Comment by codingcatgirl** [comment]
Thanks, i just fixed it.

**Comment by scientress** [comment]
btw. @turtlekiosk  The original firmware is not compatible with this PCB. I have a fork that works with the PCB we designed and also has some additional functionality.
https://github.com/evilscientress/split-flap

**Comment by btaylor112** [comment]
@evilscientress Could you clarify, is the firmware you have updated compatible with this updated PCB?

**Comment by scientress** [comment]
@btaylor112 yes. @codingcatgirl and me designed the PCB together. The firmware was modified specifically for this PCB.
