### ISSUE TITLE
Adress Jumper

### ISSUE THREAD

**Issue by JoeBerlin69** [codingcatgirl/split-flap-fae-pcb#2]
How do I use these adress jumpers? From top or bottom?
![20240701_223643](https://github.com/codingcatgirl/split-flap-fae-pcb/assets/99012149/7c0fe99e-0999-4e2c-a6bb-898d2813ba4b)
![20240701_223643](https://github.com/codingcatgirl/split-flap-fae-pcb/assets/99012149/c351eaf2-2d7f-4f6a-b878-3bfc3c279e1f)

**Comment by btaylor112** [comment]
Have you managed to resolve this? I'm having a similar issue, I'm not sure how they address?

**Comment by JoeBerlin69** [comment]
I am sorry. No i haven't a solution. I took some original pcbs from david. They work well. A built 10 split flaps in the past. They all work well. This was my first attempt (and really expensive) with this pcb and i hope, s.o. can help me with my problems told in my second issue.

**Comment by codingcatgirl** [comment]
Hey, all pins are labeled on the back of the PCB: 
![image](https://github.com/codingcatgirl/split-flap-fae-pcb/assets/3868507/6bf4aa30-7079-48a5-98f5-a3272c65b7a8)

The source code of @evilscientress' fork states: 

```c
#define ADRESSSW1 6
#define ADRESSSW2 5
#define ADRESSSW3 4
#define ADRESSSW4 3
```

Meaning tht only the top 4 jumpers currently control the address, in that order. The other jumpers can be used for something else or for more address bits in the future.

**Comment by btaylor112** [comment]
Sorry if this is a silly question - Do I use the jumpers like this?

![addressing](https://github.com/codingcatgirl/split-flap-fae-pcb/assets/65657422/b2597834-6f18-441f-a2f8-e8bf2e4b6241)

**Comment by codingcatgirl** [comment]
Those are precisely the wrong ones. You gotta use the top ones. The bottom ones are unused for now.

**Comment by btaylor112** [comment]
Like this?
![addressing](https://github.com/codingcatgirl/split-flap-fae-pcb/assets/65657422/9c147659-5073-41f5-942d-d2130572a496)

**Comment by codingcatgirl** [comment]
I'm on my way right now and can't verify it. Please just… try it out? The basic idea is right but i can't say/verify off the top of my head right now if it might be inverted or backwards.

**Comment by jvdhoeven** [comment]
I had the same issue. After some debugging I found that you have to uncomment [this](https://github.com/evilscientress/split-flap/blob/5f9a4b5b43410703144f7017ba2156e04885de44/ESPMaster/ESPMaster.ino#L38) line. After uploading the new firmware it was working. On the ESPMaster board you just leave the address blank (no jumpers). Hope this helps!

**Comment by joachimklug** [comment]
Quite late to the party but wanted to clarify as others might stumble over it:

Checking the `Unit.ino` file it states:
```C++
// Pins of I2C adress switch
#define ADRESSSW1 6
#define ADRESSSW2 5
#define ADRESSSW3 4
#define ADRESSSW4 3
```

The function `getaddress` then translates the jumpers into the address and returns it
```C++
//returns the adress of the unit as int from 0-15
int getaddress() {
  int address = !digitalRead(ADRESSSW4) + (!digitalRead(ADRESSSW3) * 2) + (!digitalRead(ADRESSSW2) * 4) + (!digitalRead(ADRESSSW1) * 8);
  return address;
}
```

This means jumpers need to be set like this:
|  | D6 | D5 | D4 | D3 |
|---|---|---|---|---|
| Unit 1 (Master) |  |  |  |  |
| Unit 2 |  |  |  | x |
| Unit 3 |  |  | x |  |
| Unit 4 |  |  | x | x |
| Unit 5 |  | x |  |  |
| Unit 6 |  | x |  | x |
| Unit 7 |  | x | x |  |
| Unit 8 |  | x | x | x |
| Unit 9 | x |  |  |  |
| Unit 10 | x |  |  | x |

Or in picture. This is the setting for Units 1-4
![jumpers](https://github.com/user-attachments/assets/902da318-f203-4884-bd21-44580904a57e)

**Debugging:** To see to which address the unit is currently set it is helpful to enable the serial monitor. After enabling and restarting the ATmega it will prompt to which address it is set. E.g. `I2CAddress: 1`
 
For my liking it is not obvious to start in the middle to set the jumpers. However when someone reads the code is it quite clear :)
I will most probably adapt my `getaddress()` function to calculate it the other way around. One could do it via the `ADRESSSW` definitions but for me `ADRESSSW1` sounds like the lowest bit.

Thanks a lot for this great PCB design!
